### ISSUE TITLE
Change Numbers 

### ISSUE THREAD

**Issue by NewtoCScience** [fta2012/ReplicatedRandom#1]
This is a question rather than an issue Mr. Ta. I read your article Predicting the next Math.random() in Java, August 2014. Great work! I am learning about the various techniques, Math Random, Next Int etc and want to know how to use my own numbers.  

For example, if I want to use these numbers from my head or through observation; 77, 31, 4, 61, 2, 50, 18, 43, 28, do I remove your numbers below and input my own numbers one at a time and run the information? Or do I combine all of the numbers? My problem is placement, like I stated I'm in the learning phase. What is the best way to structure?

Yours Original: 

```
public class ReplicatedRandom extends Random {
// Replicate the state of a Random using a single value from its nextDouble
public boolean replicateState(double nextDouble) {
    // nextDouble() is generated from ((next(26) << 27) + next(27)) / (1L << 53)
    // Inverting those operations will get us the values of next(26) and next(27)
    long numerator = (long)(nextDouble * (1L << 53));
    int first26 = (int)(numerator >>> 27);
    int last27 = (int)(numerator & ((1L << 27) - 1));
    return replicateState(first26, 26, last27, 27);
}

// Replicate the state of a Random using a single value from its nextLong
public boolean replicateState(long nextLong) {
    int last32 = (int)(nextLong & ((1L << 32) - 1));
    int first32 = (int)((nextLong - last32) >> 32);
    return replicateState(first32, 32, last32, 32);...
```

Mine # 77: 

```
public class ReplicatedRandom extends Random {
// Replicate the state of a Random using a single value from its nextDouble
public boolean replicateState(double nextDouble) {
    // nextDouble() is generated from ((next(77) <<78) + next(78)) / (1L << 156)
    // Inverting those operations will get us the values of next(77) and next(78)
    long numerator = (long)(nextDouble * (1L << 156));
    int first77 = (int)(numerator >>> 78);
    int last78 = (int)(numerator & ((1L << 78) - 1));
    return replicateState(first77, 77, last78, 78);
}

// Replicate the state of a Random using a single value from its nextLong
public boolean replicateState(long nextLong) {
    int last77= (int)(nextLong & ((1L << 77) - 1));
    int first77 = (int)((nextLong - last77) >> 77);
    return replicateState(first77, 77, last77, 77);
}
// Replicate the state of a Random using two consecutive values from its nextInt
public boolean replicateState(int firstNextInt, int secondNextInt) {
    return replicateState(firstNextInt, 77, secondNextInt, 77);
}

// Replicate the state of a Random using two consecutive values from its nextFloat
public boolean replicateState(float firstNextFloat, float secondNextFloat) {
    return replicateState((int)(firstNextFloat * (1 << 77)), 77, (int)(secondNextFloat * (1 << 77)), 77);
}
public boolean replicateState(int nextN, int n, int nextM, int m) {
    // Constants copied from java.util.Random
    final long multiplier = 0x5DEECE66DL;
    final long addend = 0xBL;
    final long mask = (1L << 48) - 1;

    long upperMOf48Mask = ((1L << m) - 1) << (48 - m);

    // next(x) is generated by taking the upper x bits of 48 bits of (oldSeed * multiplier + addend) mod (mask + 1)
    // So now we have the upper n and m bits of two consecutive calls of next(n) and next(m)
    long oldSeedUpperN = ((long)nextN << (48 - n)) & mask;
    long newSeedUpperM = ((long)nextM << (48 - m)) & mask;
```

Also, learning about bits as well. In my example of 77 above, I added 77 + 78= 156, do I need to  change all of the 48 bit parts to 156 or another number? 

Thank you very much for this much needed guidance!

NewtoCScience-

**Comment by fta2012** [comment]
Hey just to clarify the code in this repo is only useful for predicting Java's implementation of Random: http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/share/classes/java/util/Random.java.

In general it is impossible to predict the next random number that you are generating "from your head". 

But if you observe a stream of "random" numbers that you know is generated by someone calling `random.nextInt()` in Java repeatedly (either because you have access to their source code or it is the only obvious implementation):

-583455153
1310821104
824867740
-1580112227
-392419280
2048389312
-228491651
816575000
-590291990
1033958449

Then to replicate this stream you just need two consecutive numbers and use the code like so:

```
ReplicatedRandom rr = new ReplicatedRandom();
rr.replicateState(-583455153, 1310821104);
for (int i = 0; i < 10; i++) {
  System.out.println(rr.nextInt()); // Prints 824867740, -1580112227, -392419280, etc
}
```

For the example list of numbers you gave, even if it was generated by real Java program I don't think my code will help you since it is most likely generated by someone calling [random.nextInt(int n)](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/share/classes/java/util/Random.java#l386) which I don't support. The technique to replicate the state is the same but it is messier to brute force since there are many more unknown bits (depending on what the bound is) and you don't get as much information from each observation so you need a lot more observations. You can check out the README or ReplicatedRandomTest.java to see the use cases that this does support though. Hope that helped.
